# Generated by Django 3.2.20 on 2023-07-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_dates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
