# Generated by Django 3.2.20 on 2023-09-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_dates', '0003_alter_appointment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='type',
            field=models.CharField(choices=[('Online gaming', 'Online Gaming'), ('In person gaming', 'In person gaming'), ('Watch party', 'Watch party'), ('Board games', 'Board games')], default='Online gaming', max_length=50),
        ),
    ]
