# Generated by Django 3.2.20 on 2023-09-23 13:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game_dates', '0006_alter_comment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='attending',
            field=models.ManyToManyField(blank=True, related_name='event_attending', to=settings.AUTH_USER_MODEL),
        ),
    ]
